---
- name: wait to connect, might be rebooting still
  block:
    - name: wait to connect
      wait_for_connection:
        delay: 0
        timeout: 300
  rescue:
    - name: handle connection error
      fail:
        msg: "Could not connect"

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: yes

- name: Install system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - docker-ce
      - docker-compose
      - wireguard
      - wireguard-tools
    state: latest
    update_cache: true
  become: yes

# - name: Install Docker Module for Python
#   pip:
#     name: docker
#   become: yes
