---
- name: Create VPC Network
  gcp_compute_network:
    name: "{{ resource_prefix + 'gcp-ansible-network' }}"
    auto_create_subnetworks: no
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: network

- name: Create subnet within above VPC network
  gcp_compute_subnetwork:
    name: "{{ resource_prefix + 'gcp-ansible-subnet' }}"
    region: "{{ gcp_region }}"
    network: "{{ network }}"
    ip_cidr_range: "{{ ip_cidr_range }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: subnet

- name: Create firewall rule to allow port 22 and 51820 for all source IPs
  gcp_compute_firewall:
    name: "{{ resource_prefix + 'ansible-firewall' }}"
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports: ['22', '51820']
    - ip_protocol: udp
      ports: ['51820']
    target_tags:
      - "{{ resource_prefix + 'gcp-ansible' }}"
    source_ranges: ['0.0.0.0/0']
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: firewall


- name: Create firewall rule to allow port 22 and 51820 for all internal hosts
  gcp_compute_firewall:
    name: "{{ resource_prefix + 'ansible-firewall-internal' }}"
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports: ['22', '51820']
    - ip_protocol: udp
      ports: ['51820']
    target_tags:
      - "{{ resource_prefix + 'gcp-ansible' }}"
    source_tags:
      - "{{ resource_prefix + 'gcp-ansible' }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: firewall